# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate packaging/THIRD_PARTY_NOTICES.txt and packaging/version_info.txt before a build.

Run with the build environment's Python (packaging\\build.ps1 does), so it sees the packages that
get bundled. Stdlib only. Adapted from the BIOMIS team's Timelapse Video Processing (MIT).

THIRD_PARTY_NOTICES.txt: the licence and licence files of every installed package, plus the parts
that are not Python packages: Qt/PySide6 (LGPL-3.0, text included), the Python runtime, the
Bio-Formats origin of the cellSens tag names and the GUI pieces taken from Timelapse Video
Processing.
"""
from __future__ import annotations

import importlib.metadata as metadata
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING_DIR = ROOT / "packaging"
OUTPUT = PACKAGING_DIR / "THIRD_PARTY_NOTICES.txt"
VERSION_INFO = PACKAGING_DIR / "version_info.txt"

#: packages that are build or test tools only, never bundled into the app
NOT_BUNDLED = {"pip", "pyinstaller", "pyinstaller-hooks-contrib", "pytest", "pluggy", "iniconfig", "pygments",
               "altgraph", "pefile", "pywin32-ctypes", "colorama", "setuptools"}
MAX_FILE_BYTES = 1_000_000
LICENSE_KEYWORDS = ("license", "licence", "copying", "notice", "authors")

LGPL3_URL = "https://www.gnu.org/licenses/lgpl-3.0.txt"


def _is_license_like(filename: str) -> bool:
    lower = filename.lower()
    return any(keyword in lower for keyword in LICENSE_KEYWORDS)


def _read_capped(path: Path) -> str | None:
    try:
        size = path.stat().st_size
    except OSError:
        return None
    if size > MAX_FILE_BYTES:
        return f"[skipped: {size:,} bytes, over the {MAX_FILE_BYTES:,} byte cap]"
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return None


def _distribution_section(dist: metadata.Distribution, seen: set[str]) -> list[str]:
    if dist.metadata is None:
        return []
    name = dist.metadata.get("Name")
    if not name or name.lower() in NOT_BUNDLED:
        return []
    licence = dist.metadata.get("License-Expression") or dist.metadata.get("License") or "see the notices below"
    if len(licence) > 200:
        licence = licence.splitlines()[0][:200] + " (full text below)"
    lines = ["", "=" * 72, f"{name} {dist.version or ''}", f"License: {licence}"]
    home = dist.metadata.get("Home-page") or next(
        (u.split(",", 1)[1].strip() for u in (dist.metadata.get_all("Project-URL") or []) if "," in u), "")
    if home:
        lines.append(f"Source: {home}")
    for entry in dist.files or ():
        if not _is_license_like(entry.name):
            continue
        candidate = Path(dist.locate_file(entry))
        key = str(candidate)
        if key in seen or not candidate.exists():
            continue
        seen.add(key)
        text = _read_capped(candidate)
        if text:
            lines += ["", f"--- {entry} ---", text]
    return lines


def _lgpl3_text() -> str:
    """LGPL-3.0 text as a bundled package ships it, else a pointer to it."""
    for dist in metadata.distributions():
        for entry in dist.files or ():
            if "lgpl" in entry.name.lower() or entry.name.lower() in ("copying.lesser",):
                p = Path(dist.locate_file(entry))
                text = _read_capped(p) or ""
                if "GNU LESSER GENERAL PUBLIC LICENSE" in text and "Version 3" in text:
                    return text
    return f"The full text of the GNU Lesser General Public License version 3 is at {LGPL3_URL}"


def collect_notices() -> list[str]:
    lines = [
        "METADATA TRANSFER — THIRD-PARTY NOTICES",
        "",
        "Metadata Transfer is licensed under the GNU General Public License, version 3 or later",
        "(LICENSE). This file lists the licence of every component bundled with the Windows build,",
        "generated by packaging/prepare_assets.py from the build environment.",
        "",
        f"Python: {sys.version}",
    ]
    seen: set[str] = set()
    dists = sorted(metadata.distributions(), key=lambda d: ((d.metadata.get("Name") if d.metadata else "") or "").lower())
    for dist in dists:
        lines += _distribution_section(dist, seen)

    lines += ["", "=" * 72, "Qt 6 and PySide6 (Qt for Python)",
              "License: LGPL-3.0-only (open-source Qt licence; commercial licences are also offered by The Qt Company)",
              "The Qt libraries (Qt6*.dll) and the PySide6/shiboken6 modules are separate, replaceable files in the",
              "installed program's _internal folder; they are not linked into Metadata Transfer's own code, so you",
              "can replace them with your own build. Source code: https://download.qt.io/official_releases/qt/ and",
              "https://download.qt.io/official_releases/QtForPython/ (the versions are listed above).",
              "Qt Virtual Keyboard, Qt Quick/QML and the other Qt modules the app does not use are left out.", "",
              _lgpl3_text()]

    lines += ["", "=" * 72, "Bio-Formats (Open Microscopy Environment)",
              "License: GPL-2.0-or-later",
              "The descriptions of cellSens tag numbers in metadata_transfer/readers/evident_vsi/tag_names.py were",
              "taken from Bio-Formats' CellSensReader.java (Copyright (C) 2005 - 2017 Open Microscopy Environment:",
              "LOCI, University of Wisconsin - Madison; Glencoe Software, Inc.; University of Dundee), which also",
              "served as the specification of the .vsi/.ets layouts. Source: https://github.com/ome/bioformats"]

    lines += ["", "=" * 72, "Timelapse Video Processing (BIOMIS team)",
              "License: MIT",
              "The theme, icons, collapsible panels, log panel, About box, crash window, welcome page and update",
              "check of the window come from Timelapse Video Processing.",
              "Copyright (c) 2026 the Timelapse Video Processing contributors",
              "Permission is hereby granted, free of charge, to any person obtaining a copy of this software and",
              "associated documentation files (the \"Software\"), to deal in the Software without restriction,",
              "including without limitation the rights to use, copy, modify, merge, publish, distribute,",
              "sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is",
              "furnished to do so, subject to the following conditions: The above copyright notice and this",
              "permission notice shall be included in all copies or substantial portions of the Software.",
              "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT",
              "NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND",
              "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES",
              "OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN",
              "CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."]

    lines += ["", "=" * 72, "Microsoft Visual C++ runtime",
              "vcruntime140*.dll and msvcp140*.dll are redistributed under the Microsoft Visual Studio",
              "redistribution terms, as shipped with Python and Qt."]

    python_license = Path(sys.base_prefix) / "LICENSE.txt"
    if python_license.exists():
        text = _read_capped(python_license)
        if text:
            lines += ["", "=" * 72, "Python (PSF License Agreement, with the licences of bundled libraries)", text]
    return lines


def write_version_info() -> str:
    init = (ROOT / "source" / "metadata_transfer" / "__init__.py").read_text(encoding="utf-8")
    version = re.search(r'__version__ = "([^"]+)"', init).group(1)
    parts = (tuple(int(p) for p in version.split(".")) + (0, 0, 0, 0))[:4]
    affiliation = re.search(r'AFFILIATION = "([^"]+)"', init).group(1)
    text = f"""# UTF-8 -- generated by packaging/prepare_assets.py, do not edit
VSVersionInfo(
  ffi=FixedFileInfo(filevers={parts}, prodvers={parts}, mask=0x3F, flags=0x0, OS=0x40004, fileType=0x1,
                    subtype=0x0, date=(0, 0)),
  kids=[
    StringFileInfo([StringTable(u"040904B0", [
      StringStruct(u"CompanyName", u"{affiliation}"),
      StringStruct(u"FileDescription", u"Metadata Transfer"),
      StringStruct(u"FileVersion", u"{version}"),
      StringStruct(u"InternalName", u"Metadata Transfer"),
      StringStruct(u"LegalCopyright", u"Copyright (c) 2026 the Metadata Transfer contributors, GPL-3.0-or-later"),
      StringStruct(u"OriginalFilename", u"Metadata Transfer.exe"),
      StringStruct(u"ProductName", u"Metadata Transfer"),
      StringStruct(u"ProductVersion", u"{version}"),
    ])]),
    VarFileInfo([VarStruct(u"Translation", [1033, 1200])]),
  ],
)
"""
    VERSION_INFO.write_text(text, encoding="utf-8")
    return version


def main() -> int:
    PACKAGING_DIR.mkdir(exist_ok=True)
    OUTPUT.write_text("\n".join(collect_notices()), encoding="utf-8")
    version = write_version_info()
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size:,} bytes) and {VERSION_INFO.name} ({version})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
